language: ruby
rvm:
  - 2.1.5
cache: bundler
sudo: false
bundler_args: "--without development production"
before_install:
  - gem update --system
  - travis_retry gem install bundler --pre
before_script:
  - cp -f config/database.travis.yml config/database.yml
  - cp -f .env.example .env
  - bundle exec rake db:create:all
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
addons:
  code_climate:
    repo_token: d13d3cdceb1684185a66e8ce0ff3f5f4aba8a14ed3aa7417beef7854782c1859