language: ruby
rvm:
  - 2.2.2
cache: bundler
sudo: false
bundler_args: "--without development production"
before_install:
  - gem update --system
  - travis_retry gem install bundler
before_script:
  - cp -f config/database.travis.yml config/database.yml
  - cp -f .env.example .env
  - bundle exec rake db:create:all
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
env:
  - APP_DOMAIN='localhost:3000' MAILER_HOST='localhost:3000' GITHUB_SECRET='123123asdasd' GITHUB_KEY='23232sssss'